# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# This line is used to format the prompt
format = '$all'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[username]
show_always = true

[shell]
disabled = false
cmd_indicator = ' cmd'
style = 'cyan bold'
format = '[$indicator]($style) '

[[battery.display]]
threshold = 30
style = 'bold red'

[package]
disabled = true
